// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using TIMS.Inventory.SharedKernel.Common;

namespace TIMS.Inventory.SharedKernel.Entities;

public  class CardEntry : AuditableEntity
{
    public double CardId { get; set; }

    public string CardName { get; set; }

    public double? CardRate { get; set; }

    public double? SlNo { get; set; }
}