// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using TIMS.Inventory.SharedKernel.Common;

namespace TIMS.Inventory.SharedKernel.Entities;

public class OpenQuantity : AuditableEntity
{
    public int SlNo { get; set; }

    public int? ItemId { get; set; }

    public double? OpenQuantity1 { get; set; }

    public double? PurchaseRate { get; set; }

    public double? SaleRate { get; set; }

    public double? ReorderQuantity { get; set; }

    public int? CompanyYearId { get; set; }

    public int? CompanyId { get; set; }
}