// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using TIMS.Inventory.SharedKernel.Common;

namespace TIMS.Inventory.SharedKernel.Entities;

public  class QuanIt : AuditableEntity
{
    public int QuanItId { get; set; }

    public string QuanItName { get; set; }
}