// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using TIMS.Inventory.SharedKernel.Common;

namespace TIMS.Inventory.SharedKernel.Entities;

public class RuanIt:AuditableEntity 
{
    public int RuanItId { get; set; }

    public string RuanItName { get; set; }
}